//mod print;
//mod vars;
//mod types;
// mod strings;
//mod tuples;
//mod arrays;
// mod vectors;
//mod conditionals;
// mod loops;
//mod functions;
//mod pointers;
//mod structs;
//mod enums;
//mod cli;
//mod shadowing;
// mod references;
//mod passbyref;
//mod struct_serialization;
// mod hashmap;
// mod constant;
// mod options;
// mod aes;
// mod multi_maps;
// mod concurrent_multipmaps;
// mod chacha20_poly1305;
// mod rsa;
// mod hmac;
// mod errorhandling;
// mod cmac;
// mod blake2;
mod secret_sharings;

fn main() {
    println!("Hello from main.rs");

//    print::run();
//    vars::run();
//    types::run();
//    strings::run();
//    tuples::run();
//    arrays::run();
//    vectors::run();
//    conditionals::run();
//    loops::run();
//    functions::run();
//    pointers::run();
//    structs::run();
//    enums::run();
//    cli::run();
//    shadowing::run();
//    references::run();
//    passbyref::run();
//    struct_serialization::serialize_deserialize();
//    hashmap::play_hashmap();
//    constant::run();
//    options::run();
//     aes::run();
//    multi_maps::run();
//     concurrent_multipmaps::run();
//     chacha20_poly1305::run();
//     rsa::run();
//     hmac::run();
//     errorhandling::run();
//     cmac::run();
//     blake2::run();
    secret_sharings::run();
}