[package]
name = "wasm-rust-hello-world"
version = "0.1.0"
authors = ["Emad Heydari Beni <emad@heydari.be>"]
edition = "2018"

# ------- added by Emad

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.58"

# ------- added by Emad